market/urls.py
from django.conf.urls import url
from . import views

app_name = 'market'

urlpatterns = [
    # /market/
    url(r'^$', views.market, name='market'),
    url(r'^$', views.IndexView.as_view(), name='market'),

    # /market/<product_id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from market import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^market/', include('market.urls')),
    url(r'^$', views.market, name='market'),
]

market/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Product(models.Model):
    product_type = models.CharField(max_length=200)
    supplier = models.CharField(max_length=200)
    quantity = models.CharField(max_length=10)
    published_date = models.DateTimeField(
        blank=True, null=True)
    product_image = models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse('market:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.product_type + ' - ' + self.supplier

market/views.py
from django.views import generic
from .models import Product


class IndexView(generic.ListView):
    template_name = 'market/index.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.all()

class DetailView(generic.DetailView):
    model = Product
    template_name = 'market/detail.html'

website/views.py
from django.shortcuts import render
from django.views import generic
from .models import Product
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

def market(request):
    return render(request, 'market/index.html')

class IndexView(generic.ListView):
    template_name = 'market/product_list.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.all()

class DetailView(generic.DetailView):
    model = Product
    template_name = 'market/detail.html'

market/templates/market/advertentie.html
<html>
    <head>
        <title>Onze index pagina</title>
    </head>
    <body>
        <p>Hi there, this is an advertisement!</p>
        <a href="{% url 'index' %}">Index</a>
    </body>
</html>

market/templates/market/base.html
{% load staticfiles %}

<html>
    <head>
        <title>Antonio: The local food market place</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
        <link href='https://fonts.googleapis.com/css?family=Sacramento' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="{% static 'market/style.css' %}">

    </head>
    <body>
     <div class="page-header">
            <h1><a href="/">Local Food Market</a></h1>
     </div>
       {% block content %}
       {% endblock %}
    </body>
</html>

market/templates/market/detail.html
{% extends 'market/base.html' %}

{% block content %}
    <div class="product">
        <div class="date">
            {{ product.published_date }}
        </div>
        <a href="{% url 'market:index' %}"> <h3>{{ product.supplier}}'s  {{ product.product_type }}</h3> </a>
        <p> Quantity: {{ product.quantity}} </p>
        <p> Product image: {{ product.product_image }}</p>
    </div>
{% endblock %}

market/templates/market/index.html
{% extends 'market/base.html' %}

{% block content %}
    {% for product in products %}
        <div class="product">
            <a href="{% url 'market:detail' product.id %}"> <h3> {{ product.supplier}}'s  {{ product.product_type }}</h3> </a>
            <p> Quantity: {{ product.quantity}} </p>
            <p> {{ product.published_date|linebreaksbr }} </p>
        </div>
    {% endfor %}
{% endblock %}

market/templates/market/product_list.html
{% extends 'market/base.html' %}

{% block content %}
    {% for product in products %}
        <div class="product">
            <a href="{% url 'market:detail' product.id %}"> <h3> {{ product.supplier}}'s  {{ product.product_type }}</h3> </a>
            <p> Quantity: {{ product.quantity}} </p>
            <p> {{ product.published_date|linebreaksbr }} </p>
        </div>
    {% endfor %}
{% endblock %}

market/templates/market/register.html
<html>
    <head>
        <title>Registreer hier</title>
    </head>
    <body>
        <p>Hi there!</p>
        <p>It works!</p>
        <a href="{% url 'index' %}">Naar Index</a>
    </body>

website/templates/website/base.html
{% load staticfiles %}

<html>
    <head>
        <title>Antonio: The local food market place</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
        <link href='https://fonts.googleapis.com/css?family=Sacramento' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="{% static 'market/style.css' %}">

    </head>
    <body>
     <div class="page-header">
            <a href="" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <h1><a href="/">Local Food Market</a></h1>
     </div>
       {% block content %}
       {% endblock %}
    </body>
</html>

website/templates/website/index.html
{% extends 'market/base.html' %}

{% block content %}
<p>Dit is de index pagina</p>
<a href=" {% url 'market:market' %} "> Index </a>
{% endblock %}